require 'rubygems'
require 'rspec/core'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new :spec do |task|
  task.pattern = "**/spec/*_spec.rb"
end

RSpec::Core::RakeTask.new :integration do |task|
  task.pattern = "**/integration/*_spec.rb"
end

task :default => :spec
