require 'rspec/core'
require 'rspec/core/rake_task'

RSpec::Core::RakeTask.new :spec

task :clean do
  `ino clean`
end

task :build do
  `ino build`
end

task :upload do
  `ino upload`
end

task :default => [:clean, :build, :upload, :spec]
